#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EmeMangement")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertstudentdataupload(studentdataupload instance);
  partial void Updatestudentdataupload(studentdataupload instance);
  partial void Deletestudentdataupload(studentdataupload instance);
  partial void InsertTechList(TechList instance);
  partial void UpdateTechList(TechList instance);
  partial void DeleteTechList(TechList instance);
  partial void InsertAdminTable(AdminTable instance);
  partial void UpdateAdminTable(AdminTable instance);
  partial void DeleteAdminTable(AdminTable instance);
  partial void InsertStuTable(StuTable instance);
  partial void UpdateStuTable(StuTable instance);
  partial void DeleteStuTable(StuTable instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["EmeMangementConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<studentdataupload> studentdatauploads
	{
		get
		{
			return this.GetTable<studentdataupload>();
		}
	}
	
	public System.Data.Linq.Table<TechList> TechLists
	{
		get
		{
			return this.GetTable<TechList>();
		}
	}
	
	public System.Data.Linq.Table<AdminTable> AdminTables
	{
		get
		{
			return this.GetTable<AdminTable>();
		}
	}
	
	public System.Data.Linq.Table<StuTable> StuTables
	{
		get
		{
			return this.GetTable<StuTable>();
		}
	}
	
	public System.Data.Linq.Table<StuTech> StuTeches
	{
		get
		{
			return this.GetTable<StuTech>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.studentdataupload")]
public partial class studentdataupload : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _fId;
	
	private string _fName;
	
	private int _iTechId;
	
	private string _fPath;
	
	private string _fDate;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnfIdChanging(int value);
    partial void OnfIdChanged();
    partial void OnfNameChanging(string value);
    partial void OnfNameChanged();
    partial void OniTechIdChanging(int value);
    partial void OniTechIdChanged();
    partial void OnfPathChanging(string value);
    partial void OnfPathChanged();
    partial void OnfDateChanging(string value);
    partial void OnfDateChanged();
    #endregion
	
	public studentdataupload()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int fId
	{
		get
		{
			return this._fId;
		}
		set
		{
			if ((this._fId != value))
			{
				this.OnfIdChanging(value);
				this.SendPropertyChanging();
				this._fId = value;
				this.SendPropertyChanged("fId");
				this.OnfIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fName", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
	public string fName
	{
		get
		{
			return this._fName;
		}
		set
		{
			if ((this._fName != value))
			{
				this.OnfNameChanging(value);
				this.SendPropertyChanging();
				this._fName = value;
				this.SendPropertyChanged("fName");
				this.OnfNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iTechId", DbType="Int NOT NULL")]
	public int iTechId
	{
		get
		{
			return this._iTechId;
		}
		set
		{
			if ((this._iTechId != value))
			{
				this.OniTechIdChanging(value);
				this.SendPropertyChanging();
				this._iTechId = value;
				this.SendPropertyChanged("iTechId");
				this.OniTechIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fPath", DbType="VarChar(450) NOT NULL", CanBeNull=false)]
	public string fPath
	{
		get
		{
			return this._fPath;
		}
		set
		{
			if ((this._fPath != value))
			{
				this.OnfPathChanging(value);
				this.SendPropertyChanging();
				this._fPath = value;
				this.SendPropertyChanged("fPath");
				this.OnfPathChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fDate", DbType="VarChar(50)")]
	public string fDate
	{
		get
		{
			return this._fDate;
		}
		set
		{
			if ((this._fDate != value))
			{
				this.OnfDateChanging(value);
				this.SendPropertyChanging();
				this._fDate = value;
				this.SendPropertyChanged("fDate");
				this.OnfDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TechList")]
public partial class TechList : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _iTechId;
	
	private string _sTechnology;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OniTechIdChanging(int value);
    partial void OniTechIdChanged();
    partial void OnsTechnologyChanging(string value);
    partial void OnsTechnologyChanged();
    #endregion
	
	public TechList()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iTechId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int iTechId
	{
		get
		{
			return this._iTechId;
		}
		set
		{
			if ((this._iTechId != value))
			{
				this.OniTechIdChanging(value);
				this.SendPropertyChanging();
				this._iTechId = value;
				this.SendPropertyChanged("iTechId");
				this.OniTechIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sTechnology", DbType="VarChar(50)")]
	public string sTechnology
	{
		get
		{
			return this._sTechnology;
		}
		set
		{
			if ((this._sTechnology != value))
			{
				this.OnsTechnologyChanging(value);
				this.SendPropertyChanging();
				this._sTechnology = value;
				this.SendPropertyChanged("sTechnology");
				this.OnsTechnologyChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AdminTable")]
public partial class AdminTable : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _Name;
	
	private string _Email;
	
	private string _password;
	
	private string _EmpPass;
	
	private string _EmailPass;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnEmpPassChanging(string value);
    partial void OnEmpPassChanged();
    partial void OnEmailPassChanging(string value);
    partial void OnEmailPassChanged();
    #endregion
	
	public AdminTable()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50)")]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this.OnpasswordChanging(value);
				this.SendPropertyChanging();
				this._password = value;
				this.SendPropertyChanged("password");
				this.OnpasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpPass", DbType="VarChar(50)")]
	public string EmpPass
	{
		get
		{
			return this._EmpPass;
		}
		set
		{
			if ((this._EmpPass != value))
			{
				this.OnEmpPassChanging(value);
				this.SendPropertyChanging();
				this._EmpPass = value;
				this.SendPropertyChanged("EmpPass");
				this.OnEmpPassChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailPass", DbType="VarChar(50)")]
	public string EmailPass
	{
		get
		{
			return this._EmailPass;
		}
		set
		{
			if ((this._EmailPass != value))
			{
				this.OnEmailPassChanging(value);
				this.SendPropertyChanging();
				this._EmailPass = value;
				this.SendPropertyChanged("EmailPass");
				this.OnEmailPassChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StuTable")]
public partial class StuTable : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _iSNo;
	
	private string _sSID;
	
	private string _sPassword;
	
	private string _sName;
	
	private string _sMobile;
	
	private string _sCollege;
	
	private string _sUniversity;
	
	private string _sRegistrationDate;
	
	private string _sValidity;
	
	private string _sEmailId;
	
	private string _sImagePath;
	
	private string _sGender;
	
	private string _sAlternateMobile;
	
	private string _sAlternameEmail;
	
	private string _sPHouseNo;
	
	private string _sPStreet;
	
	private string _sPState;
	
	private string _sPcity;
	
	private string _sPVillage;
	
	private string _sPpincode;
	
	private string _sRhouseno;
	
	private string _sRStreet;
	
	private string _sRState;
	
	private string _sRCity;
	
	private string _sRVillage;
	
	private string _sRpincode;
	
	private string _sDob;
	
	private string _cBranch;
	
	private string _nCourse;
	
	private string _sStatus;
	
	private string _sComment;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OniSNoChanging(int value);
    partial void OniSNoChanged();
    partial void OnsSIDChanging(string value);
    partial void OnsSIDChanged();
    partial void OnsPasswordChanging(string value);
    partial void OnsPasswordChanged();
    partial void OnsNameChanging(string value);
    partial void OnsNameChanged();
    partial void OnsMobileChanging(string value);
    partial void OnsMobileChanged();
    partial void OnsCollegeChanging(string value);
    partial void OnsCollegeChanged();
    partial void OnsUniversityChanging(string value);
    partial void OnsUniversityChanged();
    partial void OnsRegistrationDateChanging(string value);
    partial void OnsRegistrationDateChanged();
    partial void OnsValidityChanging(string value);
    partial void OnsValidityChanged();
    partial void OnsEmailIdChanging(string value);
    partial void OnsEmailIdChanged();
    partial void OnsImagePathChanging(string value);
    partial void OnsImagePathChanged();
    partial void OnsGenderChanging(string value);
    partial void OnsGenderChanged();
    partial void OnsAlternateMobileChanging(string value);
    partial void OnsAlternateMobileChanged();
    partial void OnsAlternameEmailChanging(string value);
    partial void OnsAlternameEmailChanged();
    partial void OnsPHouseNoChanging(string value);
    partial void OnsPHouseNoChanged();
    partial void OnsPStreetChanging(string value);
    partial void OnsPStreetChanged();
    partial void OnsPStateChanging(string value);
    partial void OnsPStateChanged();
    partial void OnsPcityChanging(string value);
    partial void OnsPcityChanged();
    partial void OnsPVillageChanging(string value);
    partial void OnsPVillageChanged();
    partial void OnsPpincodeChanging(string value);
    partial void OnsPpincodeChanged();
    partial void OnsRhousenoChanging(string value);
    partial void OnsRhousenoChanged();
    partial void OnsRStreetChanging(string value);
    partial void OnsRStreetChanged();
    partial void OnsRStateChanging(string value);
    partial void OnsRStateChanged();
    partial void OnsRCityChanging(string value);
    partial void OnsRCityChanged();
    partial void OnsRVillageChanging(string value);
    partial void OnsRVillageChanged();
    partial void OnsRpincodeChanging(string value);
    partial void OnsRpincodeChanged();
    partial void OnsDobChanging(string value);
    partial void OnsDobChanged();
    partial void OncBranchChanging(string value);
    partial void OncBranchChanged();
    partial void OnnCourseChanging(string value);
    partial void OnnCourseChanged();
    partial void OnsStatusChanging(string value);
    partial void OnsStatusChanged();
    partial void OnsCommentChanging(string value);
    partial void OnsCommentChanged();
    #endregion
	
	public StuTable()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iSNo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int iSNo
	{
		get
		{
			return this._iSNo;
		}
		set
		{
			if ((this._iSNo != value))
			{
				this.OniSNoChanging(value);
				this.SendPropertyChanging();
				this._iSNo = value;
				this.SendPropertyChanged("iSNo");
				this.OniSNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sSID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string sSID
	{
		get
		{
			return this._sSID;
		}
		set
		{
			if ((this._sSID != value))
			{
				this.OnsSIDChanging(value);
				this.SendPropertyChanging();
				this._sSID = value;
				this.SendPropertyChanged("sSID");
				this.OnsSIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sPassword", DbType="VarChar(50)")]
	public string sPassword
	{
		get
		{
			return this._sPassword;
		}
		set
		{
			if ((this._sPassword != value))
			{
				this.OnsPasswordChanging(value);
				this.SendPropertyChanging();
				this._sPassword = value;
				this.SendPropertyChanged("sPassword");
				this.OnsPasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sName", DbType="VarChar(50)")]
	public string sName
	{
		get
		{
			return this._sName;
		}
		set
		{
			if ((this._sName != value))
			{
				this.OnsNameChanging(value);
				this.SendPropertyChanging();
				this._sName = value;
				this.SendPropertyChanged("sName");
				this.OnsNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sMobile", DbType="VarChar(20)")]
	public string sMobile
	{
		get
		{
			return this._sMobile;
		}
		set
		{
			if ((this._sMobile != value))
			{
				this.OnsMobileChanging(value);
				this.SendPropertyChanging();
				this._sMobile = value;
				this.SendPropertyChanged("sMobile");
				this.OnsMobileChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sCollege", DbType="VarChar(50)")]
	public string sCollege
	{
		get
		{
			return this._sCollege;
		}
		set
		{
			if ((this._sCollege != value))
			{
				this.OnsCollegeChanging(value);
				this.SendPropertyChanging();
				this._sCollege = value;
				this.SendPropertyChanged("sCollege");
				this.OnsCollegeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sUniversity", DbType="VarChar(50)")]
	public string sUniversity
	{
		get
		{
			return this._sUniversity;
		}
		set
		{
			if ((this._sUniversity != value))
			{
				this.OnsUniversityChanging(value);
				this.SendPropertyChanging();
				this._sUniversity = value;
				this.SendPropertyChanged("sUniversity");
				this.OnsUniversityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sRegistrationDate", DbType="VarChar(50)")]
	public string sRegistrationDate
	{
		get
		{
			return this._sRegistrationDate;
		}
		set
		{
			if ((this._sRegistrationDate != value))
			{
				this.OnsRegistrationDateChanging(value);
				this.SendPropertyChanging();
				this._sRegistrationDate = value;
				this.SendPropertyChanged("sRegistrationDate");
				this.OnsRegistrationDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sValidity", DbType="VarChar(50)")]
	public string sValidity
	{
		get
		{
			return this._sValidity;
		}
		set
		{
			if ((this._sValidity != value))
			{
				this.OnsValidityChanging(value);
				this.SendPropertyChanging();
				this._sValidity = value;
				this.SendPropertyChanged("sValidity");
				this.OnsValidityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sEmailId", DbType="VarChar(50)")]
	public string sEmailId
	{
		get
		{
			return this._sEmailId;
		}
		set
		{
			if ((this._sEmailId != value))
			{
				this.OnsEmailIdChanging(value);
				this.SendPropertyChanging();
				this._sEmailId = value;
				this.SendPropertyChanged("sEmailId");
				this.OnsEmailIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sImagePath", DbType="VarChar(5000)")]
	public string sImagePath
	{
		get
		{
			return this._sImagePath;
		}
		set
		{
			if ((this._sImagePath != value))
			{
				this.OnsImagePathChanging(value);
				this.SendPropertyChanging();
				this._sImagePath = value;
				this.SendPropertyChanged("sImagePath");
				this.OnsImagePathChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sGender", DbType="VarChar(3)")]
	public string sGender
	{
		get
		{
			return this._sGender;
		}
		set
		{
			if ((this._sGender != value))
			{
				this.OnsGenderChanging(value);
				this.SendPropertyChanging();
				this._sGender = value;
				this.SendPropertyChanged("sGender");
				this.OnsGenderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sAlternateMobile", DbType="VarChar(20)")]
	public string sAlternateMobile
	{
		get
		{
			return this._sAlternateMobile;
		}
		set
		{
			if ((this._sAlternateMobile != value))
			{
				this.OnsAlternateMobileChanging(value);
				this.SendPropertyChanging();
				this._sAlternateMobile = value;
				this.SendPropertyChanged("sAlternateMobile");
				this.OnsAlternateMobileChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sAlternameEmail", DbType="VarChar(50)")]
	public string sAlternameEmail
	{
		get
		{
			return this._sAlternameEmail;
		}
		set
		{
			if ((this._sAlternameEmail != value))
			{
				this.OnsAlternameEmailChanging(value);
				this.SendPropertyChanging();
				this._sAlternameEmail = value;
				this.SendPropertyChanged("sAlternameEmail");
				this.OnsAlternameEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sPHouseNo", DbType="VarChar(50)")]
	public string sPHouseNo
	{
		get
		{
			return this._sPHouseNo;
		}
		set
		{
			if ((this._sPHouseNo != value))
			{
				this.OnsPHouseNoChanging(value);
				this.SendPropertyChanging();
				this._sPHouseNo = value;
				this.SendPropertyChanged("sPHouseNo");
				this.OnsPHouseNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sPStreet", DbType="VarChar(50)")]
	public string sPStreet
	{
		get
		{
			return this._sPStreet;
		}
		set
		{
			if ((this._sPStreet != value))
			{
				this.OnsPStreetChanging(value);
				this.SendPropertyChanging();
				this._sPStreet = value;
				this.SendPropertyChanged("sPStreet");
				this.OnsPStreetChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sPState", DbType="VarChar(50)")]
	public string sPState
	{
		get
		{
			return this._sPState;
		}
		set
		{
			if ((this._sPState != value))
			{
				this.OnsPStateChanging(value);
				this.SendPropertyChanging();
				this._sPState = value;
				this.SendPropertyChanged("sPState");
				this.OnsPStateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sPcity", DbType="VarChar(50)")]
	public string sPcity
	{
		get
		{
			return this._sPcity;
		}
		set
		{
			if ((this._sPcity != value))
			{
				this.OnsPcityChanging(value);
				this.SendPropertyChanging();
				this._sPcity = value;
				this.SendPropertyChanged("sPcity");
				this.OnsPcityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sPVillage", DbType="VarChar(50)")]
	public string sPVillage
	{
		get
		{
			return this._sPVillage;
		}
		set
		{
			if ((this._sPVillage != value))
			{
				this.OnsPVillageChanging(value);
				this.SendPropertyChanging();
				this._sPVillage = value;
				this.SendPropertyChanged("sPVillage");
				this.OnsPVillageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sPpincode", DbType="VarChar(50)")]
	public string sPpincode
	{
		get
		{
			return this._sPpincode;
		}
		set
		{
			if ((this._sPpincode != value))
			{
				this.OnsPpincodeChanging(value);
				this.SendPropertyChanging();
				this._sPpincode = value;
				this.SendPropertyChanged("sPpincode");
				this.OnsPpincodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sRhouseno", DbType="VarChar(50)")]
	public string sRhouseno
	{
		get
		{
			return this._sRhouseno;
		}
		set
		{
			if ((this._sRhouseno != value))
			{
				this.OnsRhousenoChanging(value);
				this.SendPropertyChanging();
				this._sRhouseno = value;
				this.SendPropertyChanged("sRhouseno");
				this.OnsRhousenoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sRStreet", DbType="VarChar(50)")]
	public string sRStreet
	{
		get
		{
			return this._sRStreet;
		}
		set
		{
			if ((this._sRStreet != value))
			{
				this.OnsRStreetChanging(value);
				this.SendPropertyChanging();
				this._sRStreet = value;
				this.SendPropertyChanged("sRStreet");
				this.OnsRStreetChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sRState", DbType="VarChar(50)")]
	public string sRState
	{
		get
		{
			return this._sRState;
		}
		set
		{
			if ((this._sRState != value))
			{
				this.OnsRStateChanging(value);
				this.SendPropertyChanging();
				this._sRState = value;
				this.SendPropertyChanged("sRState");
				this.OnsRStateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sRCity", DbType="VarChar(50)")]
	public string sRCity
	{
		get
		{
			return this._sRCity;
		}
		set
		{
			if ((this._sRCity != value))
			{
				this.OnsRCityChanging(value);
				this.SendPropertyChanging();
				this._sRCity = value;
				this.SendPropertyChanged("sRCity");
				this.OnsRCityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sRVillage", DbType="VarChar(50)")]
	public string sRVillage
	{
		get
		{
			return this._sRVillage;
		}
		set
		{
			if ((this._sRVillage != value))
			{
				this.OnsRVillageChanging(value);
				this.SendPropertyChanging();
				this._sRVillage = value;
				this.SendPropertyChanged("sRVillage");
				this.OnsRVillageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sRpincode", DbType="VarChar(50)")]
	public string sRpincode
	{
		get
		{
			return this._sRpincode;
		}
		set
		{
			if ((this._sRpincode != value))
			{
				this.OnsRpincodeChanging(value);
				this.SendPropertyChanging();
				this._sRpincode = value;
				this.SendPropertyChanged("sRpincode");
				this.OnsRpincodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sDob", DbType="VarChar(20)")]
	public string sDob
	{
		get
		{
			return this._sDob;
		}
		set
		{
			if ((this._sDob != value))
			{
				this.OnsDobChanging(value);
				this.SendPropertyChanging();
				this._sDob = value;
				this.SendPropertyChanged("sDob");
				this.OnsDobChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cBranch", DbType="NChar(10)")]
	public string cBranch
	{
		get
		{
			return this._cBranch;
		}
		set
		{
			if ((this._cBranch != value))
			{
				this.OncBranchChanging(value);
				this.SendPropertyChanging();
				this._cBranch = value;
				this.SendPropertyChanged("cBranch");
				this.OncBranchChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nCourse", DbType="VarChar(50)")]
	public string nCourse
	{
		get
		{
			return this._nCourse;
		}
		set
		{
			if ((this._nCourse != value))
			{
				this.OnnCourseChanging(value);
				this.SendPropertyChanging();
				this._nCourse = value;
				this.SendPropertyChanged("nCourse");
				this.OnnCourseChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sStatus", DbType="VarChar(50)")]
	public string sStatus
	{
		get
		{
			return this._sStatus;
		}
		set
		{
			if ((this._sStatus != value))
			{
				this.OnsStatusChanging(value);
				this.SendPropertyChanging();
				this._sStatus = value;
				this.SendPropertyChanged("sStatus");
				this.OnsStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sComment", DbType="VarChar(500)")]
	public string sComment
	{
		get
		{
			return this._sComment;
		}
		set
		{
			if ((this._sComment != value))
			{
				this.OnsCommentChanging(value);
				this.SendPropertyChanging();
				this._sComment = value;
				this.SendPropertyChanged("sComment");
				this.OnsCommentChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StuTech")]
public partial class StuTech
{
	
	private string _sSID;
	
	private System.Nullable<int> _iTechId;
	
	private System.Nullable<int> _iGroupId;
	
	private System.Nullable<int> _iBid;
	
	public StuTech()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sSID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string sSID
	{
		get
		{
			return this._sSID;
		}
		set
		{
			if ((this._sSID != value))
			{
				this._sSID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iTechId", DbType="Int")]
	public System.Nullable<int> iTechId
	{
		get
		{
			return this._iTechId;
		}
		set
		{
			if ((this._iTechId != value))
			{
				this._iTechId = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iGroupId", DbType="Int")]
	public System.Nullable<int> iGroupId
	{
		get
		{
			return this._iGroupId;
		}
		set
		{
			if ((this._iGroupId != value))
			{
				this._iGroupId = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iBid", DbType="Int")]
	public System.Nullable<int> iBid
	{
		get
		{
			return this._iBid;
		}
		set
		{
			if ((this._iBid != value))
			{
				this._iBid = value;
			}
		}
	}
}
#pragma warning restore 1591
